### ISSUE TITLE
New Content

### ISSUE THREAD

**Issue by JavaJames93** [JavaJames93/Pink#18]
## Where should we put this?

`<a href="http://www.google.com/url?q=http%3A%2F%2Flearn.roche.com%2Fctmsv2%2F&sa=D&sntz=1&usg=AFQjCNFm-79VZ1EnGtfpsXWJHPme0hd__w" target="_blank">CTMS Release 2 Training Website</a>`

Check out the Release 2 Training Website for details on the changes in CTMS that were effective on 31OCT2019! This includes:

* __Core Functionalities__ (e.g. Favorites, eTMF Interface, Dynamic Reporting, User Substitution)
* __Monitoring Visit__ (e.g. Questionnaire Wizard, Reallocating Issues, Detailed Agenda/Minutes
* __Contracts Management__
* __Vendor Assessment__
* __Inventory Module__ (e.g. manufacturing part number, weight and dimension attributes, collection kits, etc)
* __Trials and Sites__ (e.g. Subject and Sample Tracking configuration, Display Actual and Planned in Trial Dialog)

**Comment by sharris27** [comment]
Content added to CTMS FAQ page
