### ISSUE TITLE
Edit eTMF Toolbox

### ISSUE THREAD

**Issue by JavaJames93** [JavaJames93/Pink#21]
## Make the following changes to the eTMF Toolbox
1. Toolbox and Guidance are the same, so we can merge those.
2. Remove  For internal training and access to eTMF, review the eTMF User Manual (under ToolBox) for further instructions. and add it as an FAQ.

**Comment by sharris27** [comment]
Added wording to introduce "toolbox" as home page. Included access instructions on toolbox page. No longer a FAQ at this time for eTMF. Changed the link behind the Veeva logo to take user directly to Veeva login screen.
