### ISSUE TITLE
eTMF Support Content Update

### ISSUE THREAD

**Issue by JavaJames93** [JavaJames93/Pink#22]
Update the graphics to match the color scheme and update the content in general

**Comment by sharris27** [comment]
Struggling to figure out how to add new images to Assets. I'm sure it is the easiest thing...
I know I need to add existing file, but when the Windows browser opens, it doesn't let me add the new files there. So I need to add them to the browser for them to be "existing".

**Comment by sharris27** [comment]
Left off trying to figure out how to:
-create a new card for IT ticket info, 
-increase size of header
-update images
-rearrange content

**Comment by sharris27** [comment]
Left off:
-Increase size font overall
-The images are great on big screen, but too small on laptop.
-Bold each papers' header

Each time I try to increase the header number, it actually makes it smaller. I need to do more searching on font size and how to make bold.

**Comment by sharris27** [comment]
<li style={{ textAlign: 'left' }}> blah blah blah </li>

**Comment by sharris27** [comment]
Done!
